DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pointer;
DROP TABLE IF EXISTS device;
DROP TABLE IF EXISTS alamat;
DROP TABLE IF EXISTS finance;
DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS volume;